### ISSUE TITLE
Create setting to disable resetting the build number

### ISSUE THREAD

**Issue by mrgnhnt96** [mrgnhnt96/pub_version_plus#1]
Currently the build number will reset automatically whenever a `major`, `minor`, or `patch` command is run. This may be undesirable for some.

Having a setting will allow this as an option so that the build number will only increase and never get reset

**Comment by frankjoshua** [comment]
Android uses the build number as the version code. So this creates problems.

**Comment by mrgnhnt96** [comment]
Completed in version 3.0.0
