### ISSUE TITLE
Version & Build Setter & Getter

### ISSUE THREAD

**Issue by Attempt3035** [mrgnhnt96/pub_version_plus#4]
Hey! Feature request here, I'm looking to use this in my CI/CD pipeline, I've set up a system where I tag a commit with a version and github actions builds and creates a release with everything as needed. Hence, it would be fantastic if I could use this to set the package to a particular version (based on the tag).

Maybe also a getter function would complete this package for use in CI/CD!

Hopefully this is relatively easy to implement if you're interested @mrgnhnt96! Otherwise, point me in the right direction and I'll give it a crack!
Cheers!

**Comment by mrgnhnt96** [comment]
Hey @Attempt3035! Sorry for the late response, recently started a new job 😅 

A getter and a setter shouldn't be too difficult to do. I wonder though, do you feel like there should be any logic restricting what you're able to set the version to? Obviously we would have a check to ensure formatting, but what about to ensure that the value always increments? I guess we could have a flag to bypass that 🤔 

Let me know what you think!

**Comment by mrgnhnt96** [comment]
I created 2 new commands, `get` and `set` in release 2.0.0. I think that this will achieve what you're looking to do. If you need anything else, feel free to open a new issue!

**Comment by Attempt3035** [comment]
Hey @mrgnhnt96, Those updates are perfect! You legend, thank you!! The system you implemented for version format check and version increase with force option is exactly what I had in mind, love it! 🚀🚀🚀
